export type UniverseCategory =
  | "market-etfs"
  | "sector-etfs"
  | "mega-cap"
  | "semiconductors"
  | "ai-infrastructure"
  | "software-cloud"
  | "cybersecurity"
  | "financials"
  | "energy"
  | "industrials"
  | "healthcare"
  | "consumer"
  | "communications"
  | "materials"
  | "utilities"
  | "real-estate"
  | "high-beta"
  | "defensive";

export type UniverseGroup = {
  id: UniverseCategory;
  name: string;
  symbols: string[];
};

export const MARKET_UNIVERSE: UniverseGroup[] = [
  {
    id: "market-etfs",
    name: "Market ETFs",
    symbols: [
      "SPY",
      "QQQ",
      "DIA",
      "IWM",
      "VOO",
      "VTI",
      "RSP",
      "MDY",
      "IJH",
      "IJR",
      "TQQQ",
      "SQQQ",
      "SOXL",
      "SOXS",
    ],
  },
  {
    id: "sector-etfs",
    name: "Sector ETFs",
    symbols: [
      "XLK",
      "XLC",
      "XLY",
      "XLP",
      "XLE",
      "XLF",
      "XLV",
      "XLI",
      "XLB",
      "XLU",
      "XLRE",
      "SMH",
      "XBI",
      "KRE",
      "XRT",
      "IYT",
      "ITA",
      "IGV",
    ],
  },
  {
    id: "mega-cap",
    name: "Mega Cap",
    symbols: [
      "AAPL",
      "MSFT",
      "NVDA",
      "AMZN",
      "META",
      "GOOGL",
      "GOOG",
      "TSLA",
      "AVGO",
      "BRK.B",
      "LLY",
      "JPM",
      "V",
      "MA",
      "WMT",
      "COST",
      "ORCL",
      "NFLX",
    ],
  },
  {
    id: "semiconductors",
    name: "Semiconductors",
    symbols: [
      "NVDA",
      "AMD",
      "AVGO",
      "TSM",
      "MU",
      "INTC",
      "QCOM",
      "ARM",
      "AMAT",
      "LRCX",
      "KLAC",
      "MRVL",
      "ADI",
      "NXPI",
      "ON",
      "MCHP",
      "ASML",
      "TXN",
    ],
  },
  {
    id: "ai-infrastructure",
    name: "AI Infrastructure",
    symbols: [
      "NVDA",
      "AVGO",
      "AMD",
      "VRT",
      "ANET",
      "SMCI",
      "DELL",
      "HPE",
      "ORCL",
      "MSFT",
      "AMZN",
      "GOOGL",
      "META",
      "PLTR",
      "CEG",
      "ETN",
      "GEV",
      "PWR",
    ],
  },
  {
    id: "software-cloud",
    name: "Software and Cloud",
    symbols: [
      "MSFT",
      "ORCL",
      "CRM",
      "NOW",
      "ADBE",
      "PLTR",
      "SNOW",
      "DDOG",
      "MDB",
      "NET",
      "TEAM",
      "WDAY",
      "SHOP",
      "UBER",
      "APP",
      "INTU",
      "PANW",
      "CRWD",
    ],
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    symbols: [
      "CRWD",
      "PANW",
      "FTNT",
      "ZS",
      "OKTA",
      "NET",
      "CYBR",
      "S",
      "TENB",
      "RBRK",
    ],
  },
  {
    id: "financials",
    name: "Financials",
    symbols: [
      "JPM",
      "BAC",
      "WFC",
      "C",
      "GS",
      "MS",
      "BLK",
      "SCHW",
      "AXP",
      "COF",
      "V",
      "MA",
      "PYPL",
      "HOOD",
      "COIN",
      "SOFI",
    ],
  },
  {
    id: "energy",
    name: "Energy",
    symbols: [
      "XOM",
      "CVX",
      "COP",
      "EOG",
      "OXY",
      "SLB",
      "HAL",
      "MPC",
      "VLO",
      "PSX",
      "KMI",
      "WMB",
      "OKE",
      "FANG",
      "EQT",
      "LNG",
    ],
  },
  {
    id: "industrials",
    name: "Industrials",
    symbols: [
      "GE",
      "GEV",
      "CAT",
      "DE",
      "BA",
      "RTX",
      "LMT",
      "NOC",
      "GD",
      "ETN",
      "HON",
      "MMM",
      "PWR",
      "URI",
      "UPS",
      "FDX",
      "UNP",
      "CSX",
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    symbols: [
      "LLY",
      "UNH",
      "ABBV",
      "JNJ",
      "MRK",
      "PFE",
      "AMGN",
      "GILD",
      "REGN",
      "VRTX",
      "ISRG",
      "TMO",
      "DHR",
      "ABT",
      "MDT",
      "CVS",
      "HUM",
      "ELV",
    ],
  },
  {
    id: "consumer",
    name: "Consumer",
    symbols: [
      "AMZN",
      "TSLA",
      "WMT",
      "COST",
      "HD",
      "LOW",
      "MCD",
      "SBUX",
      "NKE",
      "TGT",
      "TJX",
      "ROST",
      "BKNG",
      "ABNB",
      "CMG",
      "LULU",
      "RCL",
      "CCL",
    ],
  },
  {
    id: "communications",
    name: "Communication Services",
    symbols: [
      "META",
      "GOOGL",
      "GOOG",
      "NFLX",
      "DIS",
      "TMUS",
      "T",
      "VZ",
      "CMCSA",
      "CHTR",
      "SPOT",
      "ROKU",
      "SNAP",
      "PINS",
      "RBLX",
    ],
  },
  {
    id: "materials",
    name: "Materials",
    symbols: [
      "LIN",
      "FCX",
      "NEM",
      "GOLD",
      "DOW",
      "DD",
      "NUE",
      "STLD",
      "CLF",
      "AA",
      "APD",
      "SHW",
      "ECL",
      "MLM",
      "VMC",
    ],
  },
  {
    id: "utilities",
    name: "Utilities",
    symbols: [
      "NEE",
      "CEG",
      "SO",
      "DUK",
      "AEP",
      "SRE",
      "D",
      "EXC",
      "VST",
      "NRG",
      "PEG",
      "ED",
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    symbols: [
      "PLD",
      "AMT",
      "EQIX",
      "O",
      "SPG",
      "DLR",
      "WELL",
      "PSA",
      "CCI",
      "VICI",
      "CBRE",
    ],
  },
  {
    id: "high-beta",
    name: "High Beta",
    symbols: [
      "TSLA",
      "NVDA",
      "AMD",
      "PLTR",
      "COIN",
      "MSTR",
      "HOOD",
      "SOFI",
      "RIVN",
      "LCID",
      "MARA",
      "RIOT",
      "SMCI",
      "ARM",
      "APP",
      "RDDT",
      "CVNA",
      "UPST",
    ],
  },
  {
    id: "defensive",
    name: "Defensive",
    symbols: [
      "WMT",
      "COST",
      "PG",
      "KO",
      "PEP",
      "CL",
      "KMB",
      "PM",
      "MO",
      "JNJ",
      "ABBV",
      "MRK",
      "NEE",
      "SO",
      "DUK",
      "GLD",
      "SLV",
    ],
  },
];

export const SECTOR_ETF_MAP: Record<string, string[]> = {
  XLK: ["AAPL", "MSFT", "NVDA", "AVGO", "AMD", "ORCL", "CRM"],
  XLC: ["META", "GOOGL", "NFLX", "DIS", "TMUS", "VZ"],
  XLY: ["AMZN", "TSLA", "HD", "MCD", "LOW", "BKNG"],
  XLP: ["WMT", "COST", "PG", "KO", "PEP", "PM"],
  XLE: ["XOM", "CVX", "COP", "EOG", "SLB", "OXY"],
  XLF: ["JPM", "BAC", "WFC", "GS", "MS", "BLK"],
  XLV: ["LLY", "UNH", "ABBV", "JNJ", "MRK", "ISRG"],
  XLI: ["GE", "CAT", "BA", "RTX", "ETN", "HON"],
  XLB: ["LIN", "FCX", "NEM", "DOW", "NUE", "SHW"],
  XLU: ["NEE", "CEG", "SO", "DUK", "AEP", "VST"],
  XLRE: ["PLD", "AMT", "EQIX", "O", "SPG", "DLR"],
  SMH: ["NVDA", "AMD", "AVGO", "TSM", "MU", "AMAT", "LRCX"],
};

export function getUniverseGroup(
  category: UniverseCategory,
): UniverseGroup | undefined {
  return MARKET_UNIVERSE.find((group) => group.id === category);
}

export function getUniverseSymbols(category?: UniverseCategory): string[] {
  if (category) {
    return getUniverseGroup(category)?.symbols ?? [];
  }

  return Array.from(new Set(MARKET_UNIVERSE.flatMap((group) => group.symbols)));
}

export function getSectorStocks(sectorEtf: string): string[] {
  return SECTOR_ETF_MAP[sectorEtf.trim().toUpperCase()] ?? [];
}

export function getDiscoveryUniverse(limit = 250): string[] {
  const priorityCategories: UniverseCategory[] = [
    "market-etfs",
    "sector-etfs",
    "mega-cap",
    "semiconductors",
    "ai-infrastructure",
    "software-cloud",
    "financials",
    "energy",
    "industrials",
    "healthcare",
    "consumer",
    "high-beta",
  ];

  const symbols = priorityCategories.flatMap((category) =>
    getUniverseSymbols(category),
  );

  return Array.from(new Set(symbols)).slice(0, Math.max(1, limit));
}
